"use client"

import { useState, useEffect } from "react"
import { CheckCircle, XCircle, ChevronRight, RotateCcw, Trophy, Globe, Target, Lightbulb, BrainCircuit } from "lucide-react"
import { Skeleton } from "@/components/ui/skeleton"

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"

type Question = {
  id: number
  question: string
  options: string[]
  correct_answer: number
  explanation: string
  difficulty: string
}

type Quiz = {
  title: string
  title_hi: string
  questions: Question[]
  total_questions: number
}

type AnswerState = "unanswered" | "correct" | "incorrect"

const DIFFICULTY_BADGE: Record<string, string> = {
  easy:   "bg-green-500/20 text-green-300 border-green-500/30",
  medium: "bg-amber-500/20 text-amber-300 border-amber-500/30",
  hard:   "bg-red-500/20 text-red-300 border-red-500/30",
}

export function VoterQuiz() {
  const [language, setLanguage] = useState<"en" | "hi">("en")
  const [quiz, setQuiz]         = useState<Quiz | null>(null)
  const [loading, setLoading]   = useState(false)
  const [current, setCurrent]   = useState(0)
  const [selected, setSelected] = useState<number | null>(null)
  const [answers, setAnswers]   = useState<AnswerState[]>([])
  const [score, setScore]       = useState(0)
  const [finished, setFinished] = useState(false)
  const [showExp, setShowExp]   = useState(false)

  const fetchQuiz = async (lang: "en" | "hi") => {
    setLoading(true)
    setQuiz(null)
    setCurrent(0)
    setSelected(null)
    setAnswers([])
    setScore(0)
    setFinished(false)
    setShowExp(false)

    try {
      const res = await fetch(`${API_BASE}/v1/ai/quiz?language=${lang}`)
      if (!res.ok) throw new Error("Failed")
      const data = await res.json()
      setQuiz(data)
    } catch {
      // Fallback static quiz
      setQuiz(getStaticQuiz(lang))
    } finally {
      setLoading(false)
    }
  }

  const handleAnswer = (idx: number) => {
    if (selected !== null || !quiz) return
    setSelected(idx)
    setShowExp(true)
    const isCorrect = idx === quiz.questions[current].correct_answer
    const newAnswers: AnswerState[] = [...answers, isCorrect ? "correct" : "incorrect"]
    setAnswers(newAnswers)
    if (isCorrect) setScore(s => s + 1)
  }

  const handleNext = () => {
    if (!quiz) return
    if (current + 1 >= quiz.total_questions) {
      setFinished(true)
    } else {
      setCurrent(c => c + 1)
      setSelected(null)
      setShowExp(false)
    }
  }

  const handleLanguageSwitch = (lang: "en" | "hi") => {
    setLanguage(lang)
    fetchQuiz(lang)
  }

  const q = quiz?.questions[current]
  const progressPct = quiz ? ((current + (selected !== null ? 1 : 0)) / quiz.total_questions) * 100 : 0
  const pct = quiz ? Math.round((score / quiz.total_questions) * 100) : 0

  return (
    <div className="rounded-2xl border border-white/10 bg-gradient-to-br from-slate-900 to-slate-800 p-6 shadow-2xl">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex flex-col gap-0.5">
          <div className="flex items-center gap-2">
            <BrainCircuit className="w-5 h-5 text-emerald-400" />
            <h2 className="text-xl font-bold text-white">
              {language === "hi" ? "मतदाता जागरूकता प्रश्नोत्तरी" : "Voter Awareness Quiz"}
            </h2>
          </div>
          <p className="text-xs text-slate-400">
            {language === "hi" ? "Gemini AI द्वारा संचालित" : "Powered by Gemini AI"}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Globe className="h-4 w-4 text-slate-400" />
          <button
            onClick={() => handleLanguageSwitch(language === "en" ? "hi" : "en")}
            className="text-xs px-3 py-1.5 rounded-full border border-orange-500/40 text-orange-300 hover:bg-orange-500/20 transition-all"
          >
            {language === "en" ? "हिंदी" : "English"}
          </button>
        </div>
      </div>

      {/* Start State */}
      {!quiz && !loading && (
        <div className="text-center py-10">
          <div className="flex justify-center mb-4">
            <div className="w-16 h-16 rounded-full bg-emerald-500/10 flex items-center justify-center border border-emerald-500/20">
              <Target className="w-8 h-8 text-emerald-400" />
            </div>
          </div>
          <p className="text-slate-300 mb-6 max-w-sm mx-auto">
            {language === "hi"
              ? "भारतीय चुनाव प्रक्रिया के बारे में अपना ज्ञान परखें। 5 प्रश्न, Gemini AI द्वारा तैयार।"
              : "Test your knowledge of the Indian election process. 5 questions, dynamically generated by Gemini AI."}
          </p>
          <button
            onClick={() => fetchQuiz(language)}
            className="px-6 py-3 rounded-full bg-gradient-to-r from-orange-500 to-amber-500 text-white font-semibold hover:scale-105 transition-all shadow-lg shadow-orange-500/25"
          >
            {language === "hi" ? "प्रश्नोत्तरी शुरू करें →" : "Start Quiz →"}
          </button>
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="space-y-4 py-4" aria-busy="true" aria-live="polite">
          <div className="flex items-center gap-3 mb-6">
            <Skeleton className="h-2 flex-1 rounded-full bg-slate-700" />
            <Skeleton className="h-4 w-8 bg-slate-700" />
          </div>
          <Skeleton className="h-6 w-1/4 bg-slate-700 mb-2" />
          <Skeleton className="h-12 w-full bg-slate-700 mb-6" />
          
          <div className="space-y-3">
            <Skeleton className="h-14 w-full rounded-xl bg-slate-700" />
            <Skeleton className="h-14 w-full rounded-xl bg-slate-700" />
            <Skeleton className="h-14 w-full rounded-xl bg-slate-700" />
            <Skeleton className="h-14 w-full rounded-xl bg-slate-700" />
          </div>
          <p className="text-center text-slate-400 text-sm mt-6 animate-pulse">
            {language === "hi" ? "Gemini प्रश्न तैयार कर रहा है..." : "Gemini is generating questions..."}
          </p>
        </div>
      )}

      {/* Finished */}
      {finished && quiz && (
        <div className="text-center py-6">
          <Trophy className="h-16 w-16 text-amber-400 mx-auto mb-4" />
          <h3 className="text-2xl font-bold text-white mb-1">
            {pct >= 80 ? "🎉 Excellent!" : pct >= 60 ? "👏 Good Job!" : "📚 Keep Learning!"}
          </h3>
          <p className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-orange-400 to-amber-400 mb-2">
            {score}/{quiz.total_questions}
          </p>
          <p className="text-slate-400 mb-6">{pct}% correct</p>

          {/* Score breakdown */}
          <div className="flex justify-center gap-2 mb-6">
            {answers.map((a, i) => (
              <div key={i} className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${a === "correct" ? "bg-green-500" : "bg-red-500"}`}>
                {a === "correct" ? "✓" : "✗"}
              </div>
            ))}
          </div>

          <button
            onClick={() => fetchQuiz(language)}
            className="flex items-center gap-2 mx-auto px-5 py-2.5 rounded-full border border-orange-500/40 text-orange-300 hover:bg-orange-500/20 transition-all"
          >
            <RotateCcw className="h-4 w-4" />
            {language === "hi" ? "फिर से खेलें" : "Try Again"}
          </button>
        </div>
      )}

      {/* Active Question */}
      {quiz && q && !finished && !loading && (
        <div className="space-y-4">
          {/* Progress bar */}
          <div className="flex items-center gap-3 mb-4" role="progressbar" aria-valuenow={Math.round(progressPct)} aria-valuemin={0} aria-valuemax={100}>
            <div className="flex-1 h-1.5 bg-slate-700 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-orange-500 to-amber-500 rounded-full transition-all duration-500"
                style={{ width: `${progressPct}%` }}
              />
            </div>
            <span className="text-xs text-slate-400 shrink-0" aria-label={`Question ${current + 1} of ${quiz.total_questions}`}>{current + 1}/{quiz.total_questions}</span>
          </div>

          {/* Question */}
          <div className="flex items-start gap-2 mb-1">
            <span className={`text-xs px-2 py-0.5 rounded-full border ${DIFFICULTY_BADGE[q.difficulty] || DIFFICULTY_BADGE.medium}`}>
              {q.difficulty}
            </span>
          </div>
          <h3 id="quiz-question-heading" className="text-base font-semibold text-white leading-snug">{q.question}</h3>

          {/* Options */}
          <div className="grid gap-2" role="radiogroup" aria-labelledby="quiz-question-heading">
            {q.options.map((option, idx) => {
              let style = "border-slate-600/60 bg-slate-800/60 text-slate-300 hover:border-orange-500/50 hover:bg-orange-500/10"
              if (selected !== null) {
                if (idx === q.correct_answer) style = "border-green-500 bg-green-500/15 text-green-300"
                else if (idx === selected && idx !== q.correct_answer) style = "border-red-500 bg-red-500/15 text-red-300"
                else style = "border-slate-700 bg-slate-800/40 text-slate-500"
              }
              return (
                <button
                  key={idx}
                  role="radio"
                  aria-checked={selected === idx}
                  onClick={() => handleAnswer(idx)}
                  disabled={selected !== null}
                  className={`w-full text-left px-4 py-3 rounded-xl border text-sm font-medium transition-all duration-200 flex items-center gap-3 ${style} disabled:cursor-default`}
                >
                  <span className="shrink-0 w-6 h-6 rounded-full border border-current flex items-center justify-center text-xs">
                    {String.fromCharCode(65 + idx)}
                  </span>
                  {option}
                  {selected !== null && idx === q.correct_answer && (
                    <CheckCircle className="h-4 w-4 ml-auto text-green-400 shrink-0" />
                  )}
                  {selected === idx && idx !== q.correct_answer && (
                    <XCircle className="h-4 w-4 ml-auto text-red-400 shrink-0" />
                  )}
                </button>
              )
            })}
          </div>

          {/* Explanation */}
          {showExp && (
            <div className={`rounded-xl p-4 border text-sm ${selected === q.correct_answer ? "border-green-500/30 bg-green-500/10 text-green-200" : "border-red-500/30 bg-red-500/10 text-red-200"}`}>
              <p className="font-semibold mb-1 flex items-center gap-1.5"><Lightbulb className="w-4 h-4" /> {language === "hi" ? "स्पष्टीकरण:" : "Explanation:"}</p>
              <p className="leading-relaxed opacity-90">{q.explanation}</p>
            </div>
          )}

          {/* Next Button */}
          {selected !== null && (
            <button
              onClick={handleNext}
              className="w-full py-3 rounded-xl bg-gradient-to-r from-orange-500 to-amber-500 text-white font-semibold flex items-center justify-center gap-2 hover:opacity-90 transition-opacity mt-2"
            >
              {current + 1 >= quiz.total_questions
                ? (
                  <span className="flex items-center gap-2">
                    {language === "hi" ? "परिणाम देखें" : "See Results"} <Trophy className="w-4 h-4" />
                  </span>
                )
                : (language === "hi" ? "अगला प्रश्न" : "Next Question")}
              {current + 1 < quiz.total_questions && <ChevronRight className="h-4 w-4" />}
            </button>
          )}
        </div>
      )}
    </div>
  )
}

// ── Static Fallback ────────────────────────────────────────────────────────────
function getStaticQuiz(lang: "en" | "hi"): Quiz {
  if (lang === "hi") return {
    title: "India Election Awareness Quiz",
    title_hi: "भारत चुनाव जागरूकता प्रश्नोत्तरी",
    total_questions: 5,
    questions: [
      { id: 1, question: "भारत में मतदान की न्यूनतम आयु क्या है?", options: ["16 वर्ष", "18 वर्ष", "21 वर्ष", "25 वर्ष"], correct_answer: 1, explanation: "61वें संवैधानिक संशोधन (1989) से मतदान आयु 21 से घटाकर 18 वर्ष की गई।", difficulty: "easy" },
      { id: 2, question: "NOTA का अर्थ क्या है?", options: ["None Of The Allowed", "None Of The Above", "No Other Than Authorized", "National Option To Abstain"], correct_answer: 1, explanation: "NOTA = None Of The Above। 2013 में सुप्रीम कोर्ट के आदेश से लागू हुआ।", difficulty: "easy" },
      { id: 3, question: "नए मतदाता पंजीकरण के लिए कौन सा फॉर्म है?", options: ["Form 7", "Form 8", "Form 6", "Form 4"], correct_answer: 2, explanation: "Form 6 नए मतदाता पंजीकरण के लिए है। Form 7 नाम हटाने के लिए है।", difficulty: "medium" },
      { id: 4, question: "आदर्श आचार संहिता कब लागू होती है?", options: ["मतदान के दिन", "चुनाव घोषणा की तिथि से", "एक सप्ताह पहले", "नामांकन तिथि से"], correct_answer: 1, explanation: "MCC चुनाव कार्यक्रम घोषणा की तिथि से परिणाम तक लागू रहती है।", difficulty: "medium" },
      { id: 5, question: "EVM का पूरा नाम क्या है?", options: ["Electronic Voter Machine", "Electronic Voting Machine", "Electoral Vote Monitor", "Election Verification Module"], correct_answer: 1, explanation: "EVM = Electronic Voting Machine। 2004 से सभी क्षेत्रों में उपयोग।", difficulty: "easy" },
    ],
  }
  return {
    title: "India Election Awareness Quiz",
    title_hi: "भारत चुनाव जागरूकता प्रश्नोत्तरी",
    total_questions: 5,
    questions: [
      { id: 1, question: "What is the minimum voting age in India?", options: ["16 years", "18 years", "21 years", "25 years"], correct_answer: 1, explanation: "The 61st Amendment (1989) lowered the voting age from 21 to 18 years.", difficulty: "easy" },
      { id: 2, question: "What does NOTA stand for?", options: ["None Of The Allowed", "None Of The Above", "No Other Than Authorized", "National Option To Abstain"], correct_answer: 1, explanation: "NOTA = None Of The Above. Introduced in 2013 via Supreme Court ruling.", difficulty: "easy" },
      { id: 3, question: "Which form is used to register as a new voter?", options: ["Form 7", "Form 8", "Form 6", "Form 4"], correct_answer: 2, explanation: "Form 6 is for new voter registration. Form 7 is for deletion.", difficulty: "medium" },
      { id: 4, question: "When does the Model Code of Conduct come into effect?", options: ["On polling day", "From the date of election announcement", "One week before polling", "From the last date of nomination"], correct_answer: 1, explanation: "MCC is enforced from the announcement date until results are declared.", difficulty: "medium" },
      { id: 5, question: "How long are polling booths open on election day?", options: ["6 AM – 4 PM", "7 AM – 6 PM", "8 AM – 5 PM", "9 AM – 7 PM"], correct_answer: 1, explanation: "Polling booths typically open at 7 AM and close at 6 PM.", difficulty: "easy" },
    ],
  }
}
